spring:
  application:
    name: userManagement
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/usermanagement
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 20
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
jwt:
  secret: QY7+kf+byv12hzyWOZzDxm1oqjqY5Kt1wftPDiid58Q=
  expiration: 3600
server:
  port: 8088
